### ISSUE TITLE
esp32

### ISSUE THREAD

**Issue by elBit0r** [gilman88/xmodem-lib#3]
Hello Thomas, I tried to compile the library on ESP32, but unfortunately, it gives an error. I would like to know if this is a known issue or not. This library is very useful. In my case, I would like to send files from the SD card connected to the ESP32 using the serial port.

**Comment by gilman88** [comment]
I don't have any ESP32 hardware so I was not aware of this. I tried pulling down the esp32:esp32:nodemcu-32s core to compile against in a test project I have and things seem to compile without issue.
In a different project that uses this library I can see some differences with incompatible return types from the esp32 core (portOutputRegister function) from the arduino nano I use but that is not in the xmodem library code

**Comment by geoffbrucepayne** [comment]
Hi I was able to compile and load onto ESP32 dev kit, though I had to reference the Github repository rather than the library manager.  In my case I'm using Platformio and set a `lib_deps = https://github.com/gilman88/xmodem-lib.git`.

I raised a separate issue about the linkage between the library manager which seems different than the Github repo.

**Comment by gilman88** [comment]
Thanks looks like I made a mistake while releasing 1.0.2 so the Arduino Library list didn't pick it up. It should be resolved on my side now and in the arduino library list in the near future
